<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [126]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [127]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [128]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [129]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [130]:
scalar.ndim

0

In [131]:
# Get tensor back as python int
scalar.item()

7

## Vectors

In [132]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [133]:
vector.ndim

1

In [134]:
vector.shape

torch.Size([2])

## MATRIX

In [135]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [136]:
MATRIX.ndim

2

In [137]:
MATRIX.shape

torch.Size([2, 2])

In [138]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


## TENSOR

In [139]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [140]:
TENSOR.ndim

3

In [141]:
TENSOR.shape

torch.Size([1, 3, 3])

In [142]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [143]:
TENSOR2.ndim

3

In [144]:
TENSOR2.shape

torch.Size([2, 3, 3])

### RAndom TenSors
Neural Network start learning with Random Tensors

In [145]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2039, 0.1123, 0.9447, 0.3488],
        [0.8127, 0.5656, 0.5333, 0.8769],
        [0.9403, 0.1399, 0.0028, 0.7487]])

In [146]:
random_tensor.ndim

2

In [147]:
random_tensor2 = torch.rand(5, 5, 10)
random_tensor2

tensor([[[0.2325, 0.8734, 0.7138, 0.7342, 0.8840, 0.1866, 0.0495, 0.3217,
          0.6591, 0.3495],
         [0.9361, 0.7672, 0.6121, 0.3493, 0.5056, 0.2405, 0.7663, 0.3039,
          0.8734, 0.2987],
         [0.5279, 0.8040, 0.8309, 0.6469, 0.5986, 0.3186, 0.1395, 0.6960,
          0.2933, 0.5791],
         [0.3029, 0.2217, 0.2449, 0.0675, 0.6379, 0.8219, 0.5601, 0.9509,
          0.4873, 0.2136],
         [0.8819, 0.7087, 0.6192, 0.0846, 0.1168, 0.4357, 0.6181, 0.9213,
          0.6218, 0.7597]],

        [[0.1513, 0.1940, 0.1926, 0.7972, 0.5377, 0.4879, 0.9763, 0.0602,
          0.4992, 0.6029],
         [0.9409, 0.3680, 0.1802, 0.5083, 0.3194, 0.4256, 0.7545, 0.8754,
          0.9100, 0.8440],
         [0.7605, 0.7623, 0.6764, 0.8688, 0.9388, 0.9182, 0.8639, 0.0406,
          0.3364, 0.4848],
         [0.0613, 0.8512, 0.1866, 0.6943, 0.5594, 0.0419, 0.7539, 0.6434,
          0.4983, 0.6378],
         [0.8519, 0.9488, 0.0236, 0.7723, 0.6527, 0.5375, 0.2819, 0.7080,
          0.080

In [148]:
random_tensor2.ndim

3

In [149]:
# Creat a random tensor similar to shape of image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h,w,color channels
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [150]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [151]:
torch.rand(3,4) * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [152]:
zero.dtype

torch.float32

In [153]:
# Ones
one = torch.ones(5,6,7)
one

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1.,

In [154]:
one.dtype

torch.float32

### creating range of tensors and tensor like

In [155]:
torch.range(1,10)

<ipython-input-155-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [156]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
torch.arange(start=1, end=1000, step=63)

tensor([  1,  64, 127, 190, 253, 316, 379, 442, 505, 568, 631, 694, 757, 820,
        883, 946])

### Tensor like

In [158]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [159]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=None)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [160]:
float_16_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 4., 5., 6.], dtype=torch.float16)
torch.float16


In [161]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device=None,
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [162]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device='cpu',
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [163]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5., 6.], dtype=torch.float16)

In [164]:
m = float_16_tensor * float_32_tensor
print(m)
print(m.dtype)

tensor([ 9., 16., 25., 36.])
torch.float32


In [165]:
m = float_16_tensor * float_16_tensor
m

tensor([ 9., 16., 25., 36.], dtype=torch.float16)

In [166]:
int_32_tensor = torch.tensor([3, 7, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

Most important Error

In [167]:
# float_32_tensor * int_32_tensor 

In [168]:
# int_32_tensor * float_16_tensor

### Getting information from Tensors 

In [169]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2420, 0.3765, 0.3165, 0.1143],
        [0.8762, 0.9380, 0.2959, 0.7195],
        [0.3242, 0.2496, 0.3843, 0.4508]])

In [170]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2420, 0.3765, 0.3165, 0.1143],
        [0.8762, 0.9380, 0.2959, 0.7195],
        [0.3242, 0.2496, 0.3843, 0.4508]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

In [171]:
%%time
my_tensor = torch.tensor([1, 3, 5])
my_tensor + 10

CPU times: user 189 µs, sys: 0 ns, total: 189 µs
Wall time: 200 µs


tensor([11, 13, 15])

In [172]:
%%time
my_tensor * 10

CPU times: user 1.04 ms, sys: 0 ns, total: 1.04 ms
Wall time: 2.53 ms


tensor([10, 30, 50])

In [173]:
%%time
my_tensor - 10

CPU times: user 1.07 ms, sys: 6 µs, total: 1.08 ms
Wall time: 2.06 ms


tensor([-9, -7, -5])

### Built in functions 

In [174]:
%%time
torch.mul(my_tensor , 10)

CPU times: user 1.12 ms, sys: 1 µs, total: 1.12 ms
Wall time: 2.58 ms


tensor([10, 30, 50])

In [175]:
%%time
torch.add(my_tensor, 10)

CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 2.02 ms


tensor([11, 13, 15])

### Matrix Multiplication

In [176]:
print(my_tensor, "*", my_tensor)
my_tensor * my_tensor

tensor([1, 3, 5]) * tensor([1, 3, 5])


tensor([ 1,  9, 25])

In [177]:
torch.matmul(my_tensor, my_tensor)

tensor(35)

In [178]:
#matrix multi by hand
1*1 + 3*3 + 5*5

35

In [179]:
%%time
v=0
for i in my_tensor:
  v += i * i
print(v) 

tensor(35)
CPU times: user 638 µs, sys: 0 ns, total: 638 µs
Wall time: 648 µs


In [180]:
%%time
torch.matmul(my_tensor, my_tensor)

CPU times: user 82 µs, sys: 0 ns, total: 82 µs
Wall time: 87 µs


tensor(35)

In [181]:
%%time
my_tensor @ my_tensor

CPU times: user 85 µs, sys: 0 ns, total: 85 µs
Wall time: 89.9 µs


tensor(35)

### Shape ERRORS!!!!

In [182]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [183]:
tensor_B = torch.tensor([
  [7, 10],
  [8, 11],
  [9, 12] 
])

tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [186]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [189]:
tensor_B.T , tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [190]:
tensor_B.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [211]:
try:
  torch.mm(tensor_A, tensor_B)
except:
  print(r"""RuntimeError                              Traceback (most recent call last)
<ipython-input-210-d49420418508> in <module>
----> 1 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)""")

RuntimeError                              Traceback (most recent call last)
<ipython-input-210-d49420418508> in <module>
----> 1 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [191]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [194]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [193]:
tensor_A.shape , tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### finding the min, max, mean, sum, etc

In [195]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [196]:
# min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [197]:
# max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [208]:
# mean
try:
  torch.mean(x)
except:
  print("change dtype")
  print("RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long")

change dtype
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [201]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [207]:
# mean
try:
  x.mean()
except:
  print("change dtype")
  print("mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long")

change dtype
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [204]:
x.type(torch.float32).mean()

tensor(45.)

### Finding the position min and max

In [219]:
y =torch.tensor( [22 , 10 , 20 , 0, 30, 40, 5, 60, 70, 89, 449])
y

tensor([ 22,  10,  20,   0,  30,  40,   5,  60,  70,  89, 449])

In [222]:
# find the position of min val and return the index of min val
y.argmin()

tensor(3)

In [221]:
y[3]

tensor(0)

In [224]:
# find the position of max val and return the index of max val
y.argmax()

tensor(10)

In [225]:
y[10]

tensor(449)

### Reshaping, Stacking, Squeezing & UNsqueezing tensors