<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [2]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

## Vectors

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

## MATRIX

In [11]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


## TENSOR

In [15]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [19]:
TENSOR2.ndim

3

In [20]:
TENSOR2.shape

torch.Size([2, 3, 3])

### RAndom TenSors
Neural Network start learning with Random Tensors

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4107, 0.7555, 0.5780, 0.3311],
        [0.0230, 0.5723, 0.1941, 0.9875],
        [0.6191, 0.7411, 0.5917, 0.1038]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor2 = torch.rand(5, 5, 10)
random_tensor2

tensor([[[0.8707, 0.0418, 0.2262, 0.3794, 0.7295, 0.6928, 0.8004, 0.5709,
          0.4098, 0.1816],
         [0.6670, 0.5653, 0.3726, 0.9985, 0.5944, 0.5651, 0.9345, 0.4035,
          0.0258, 0.2593],
         [0.8351, 0.9430, 0.5185, 0.9419, 0.2380, 0.1016, 0.2929, 0.1065,
          0.0036, 0.6087],
         [0.3192, 0.2694, 0.0222, 0.9645, 0.1260, 0.8484, 0.1436, 0.1953,
          0.2330, 0.4288],
         [0.8724, 0.8822, 0.3574, 0.0257, 0.4490, 0.4973, 0.3529, 0.1808,
          0.2661, 0.9546]],

        [[0.0462, 0.8647, 0.2356, 0.1474, 0.1160, 0.2472, 0.2979, 0.2285,
          0.1932, 0.4129],
         [0.5352, 0.6181, 0.3783, 0.4959, 0.6963, 0.0433, 0.7510, 0.2190,
          0.9650, 0.9685],
         [0.2837, 0.7609, 0.2249, 0.2028, 0.4704, 0.4388, 0.3379, 0.7650,
          0.0273, 0.3389],
         [0.6424, 0.6023, 0.9706, 0.5086, 0.8395, 0.3920, 0.4112, 0.7286,
          0.1251, 0.6410],
         [0.6110, 0.8912, 0.4990, 0.3099, 0.4319, 0.3300, 0.7347, 0.0238,
          0.406

In [24]:
random_tensor2.ndim

3

In [25]:
# Creat a random tensor similar to shape of image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h,w,color channels
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [26]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.rand(3,4) * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zero.dtype

torch.float32

In [29]:
# Ones
one = torch.ones(5,6,7)
one

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1.,

In [30]:
one.dtype

torch.float32

## creating range of tensors and tensor like

In [31]:
torch.range(1,10)

<ipython-input-31-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
torch.arange(start=1, end=1000, step=63)

tensor([  1,  64, 127, 190, 253, 316, 379, 442, 505, 568, 631, 694, 757, 820,
        883, 946])

## Tensor like

In [36]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])