<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

Vectors

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

MATRIX

In [10]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


TENSOR

In [14]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [18]:
TENSOR2.ndim

3

In [19]:
TENSOR2.shape

torch.Size([2, 3, 3])