<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [2]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

## Vectors

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

## MATRIX

In [11]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


## TENSOR

In [15]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [19]:
TENSOR2.ndim

3

In [20]:
TENSOR2.shape

torch.Size([2, 3, 3])

### RAndom TenSors
Neural Network start learning with Random Tensors

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7233, 0.2637, 0.9299, 0.2076],
        [0.8899, 0.2666, 0.0394, 0.1138],
        [0.4290, 0.9265, 0.2689, 0.7140]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor2 = torch.rand(5, 5, 10)
random_tensor2

tensor([[[0.7293, 0.0432, 0.6631, 0.8685, 0.8942, 0.1269, 0.2994, 0.5454,
          0.2241, 0.6171],
         [0.2867, 0.6893, 0.6985, 0.3497, 0.3980, 0.3540, 0.4050, 0.4472,
          0.2974, 0.0734],
         [0.4327, 0.7653, 0.0912, 0.2498, 0.7066, 0.7770, 0.2639, 0.4624,
          0.4124, 0.1347],
         [0.1367, 0.3970, 0.5107, 0.5951, 0.5985, 0.9161, 0.2215, 0.7033,
          0.0560, 0.5963],
         [0.2305, 0.0597, 0.5258, 0.4588, 0.6955, 0.2915, 0.2009, 0.8269,
          0.1094, 0.5791]],

        [[0.4843, 0.7136, 0.4914, 0.6473, 0.4033, 0.8610, 0.0165, 0.3521,
          0.3598, 0.1697],
         [0.7715, 0.2480, 0.0997, 0.7091, 0.3223, 0.3719, 0.9912, 0.4082,
          0.9598, 0.1066],
         [0.8260, 0.5950, 0.7845, 0.0228, 0.4232, 0.7128, 0.2442, 0.5572,
          0.6770, 0.7937],
         [0.9498, 0.4159, 0.1807, 0.2372, 0.8269, 0.0204, 0.8879, 0.5176,
          0.0533, 0.3315],
         [0.9002, 0.5535, 0.0056, 0.6750, 0.1456, 0.3265, 0.3018, 0.2810,
          0.805

In [24]:
random_tensor2.ndim

3

In [25]:
# Creat a random tensor similar to shape of image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h,w,color channels
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [26]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.rand(3,4) * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zero.dtype

torch.float32

In [32]:
# Ones
one = torch.ones(5,6,7)
one

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1.,

In [34]:
one.dtype

torch.float32