<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

## Vectors

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

## MATRIX

In [10]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


## TENSOR

In [14]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [18]:
TENSOR2.ndim

3

In [19]:
TENSOR2.shape

torch.Size([2, 3, 3])

### RAndom TenSors
Neural Network start learning with Random Tensors

In [20]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4275, 0.8372, 0.8726, 0.4489],
        [0.2352, 0.6130, 0.7470, 0.4717],
        [0.6691, 0.4253, 0.9251, 0.0451]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor2 = torch.rand(5, 5, 10)
random_tensor2

tensor([[[6.1259e-01, 6.1251e-01, 1.1836e-01, 3.9390e-01, 3.0896e-01,
          8.2138e-01, 5.5063e-01, 6.8581e-01, 9.9294e-01, 7.7115e-01],
         [1.2400e-01, 6.6579e-01, 7.4886e-01, 4.0582e-01, 2.3577e-02,
          2.2158e-01, 9.0421e-01, 4.8763e-01, 5.2583e-01, 2.0515e-02],
         [2.0760e-01, 1.3126e-01, 8.9533e-01, 1.4783e-01, 3.1166e-01,
          8.4894e-01, 7.8993e-01, 2.2267e-01, 4.7783e-01, 1.2703e-02],
         [6.0697e-01, 6.8717e-01, 2.6466e-01, 8.7330e-01, 7.3207e-03,
          3.7315e-01, 5.7325e-01, 9.4534e-01, 8.0272e-01, 7.6483e-01],
         [9.3605e-01, 8.9092e-01, 8.9891e-01, 4.5342e-01, 3.6073e-01,
          8.8803e-01, 8.1954e-02, 5.3273e-01, 4.5060e-01, 8.2912e-01]],

        [[5.4006e-01, 2.7363e-01, 4.3350e-01, 7.8321e-03, 3.0705e-01,
          6.7625e-01, 3.2960e-01, 7.3632e-02, 2.6007e-02, 6.7426e-01],
         [8.7567e-01, 9.0980e-01, 5.8137e-01, 6.7002e-01, 8.4781e-02,
          6.6187e-01, 2.2239e-01, 9.6469e-01, 7.8054e-01, 2.2280e-01],
         [4

In [23]:
random_tensor2.ndim

3

In [24]:
# Creat a random tensor similar to shape of image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h,w,color channels
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [25]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.rand(3,4) * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zero.dtype

torch.float32

In [28]:
# Ones
one = torch.ones(5,6,7)
one

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1.,

In [29]:
one.dtype

torch.float32

### creating range of tensors and tensor like

In [30]:
torch.range(1,10)

<ipython-input-30-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
torch.arange(start=1, end=1000, step=63)

tensor([  1,  64, 127, 190, 253, 316, 379, 442, 505, 568, 631, 694, 757, 820,
        883, 946])

### Tensor like

In [33]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [34]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=None)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [35]:
float_16_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 4., 5., 6.], dtype=torch.float16)
torch.float16


In [36]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device=None,
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [37]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device='cpu',
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [38]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5., 6.], dtype=torch.float16)

In [39]:
m = float_16_tensor * float_32_tensor
print(m)
print(m.dtype)

tensor([ 9., 16., 25., 36.])
torch.float32


In [40]:
m = float_16_tensor * float_16_tensor
m

tensor([ 9., 16., 25., 36.], dtype=torch.float16)

In [41]:
int_32_tensor = torch.tensor([3, 7, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

Most important Error

In [42]:
# float_32_tensor * int_32_tensor 

In [43]:
# int_32_tensor * float_16_tensor

### Getting information from Tensors 

In [44]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6513, 0.5568, 0.8505, 0.9829],
        [0.3375, 0.0919, 0.9750, 0.4495],
        [0.0566, 0.6317, 0.0173, 0.9861]])

In [45]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6513, 0.5568, 0.8505, 0.9829],
        [0.3375, 0.0919, 0.9750, 0.4495],
        [0.0566, 0.6317, 0.0173, 0.9861]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

In [46]:
%%time
my_tensor = torch.tensor([1, 3, 5])
my_tensor + 10

CPU times: user 384 µs, sys: 0 ns, total: 384 µs
Wall time: 6.41 ms


tensor([11, 13, 15])

In [47]:
%%time
my_tensor * 10

CPU times: user 92 µs, sys: 15 µs, total: 107 µs
Wall time: 244 µs


tensor([10, 30, 50])

In [48]:
%%time
my_tensor - 10

CPU times: user 249 µs, sys: 41 µs, total: 290 µs
Wall time: 2.65 ms


tensor([-9, -7, -5])

### Built in functions 

In [49]:
%%time
torch.mul(my_tensor , 10)

CPU times: user 106 µs, sys: 18 µs, total: 124 µs
Wall time: 130 µs


tensor([10, 30, 50])

In [50]:
%%time
torch.add(my_tensor, 10)

CPU times: user 1.59 ms, sys: 15 µs, total: 1.61 ms
Wall time: 4.06 ms


tensor([11, 13, 15])

### Matrix Multiplication

In [51]:
print(my_tensor, "*", my_tensor)
my_tensor * my_tensor

tensor([1, 3, 5]) * tensor([1, 3, 5])


tensor([ 1,  9, 25])

In [52]:
torch.matmul(my_tensor, my_tensor)

tensor(35)

In [53]:
#matrix multi by hand
1*1 + 3*3 + 5*5

35

In [54]:
%%time
v=0
for i in my_tensor:
  v += i * i
print(v) 

tensor(35)
CPU times: user 685 µs, sys: 931 µs, total: 1.62 ms
Wall time: 1.79 ms


In [55]:
%%time
torch.matmul(my_tensor, my_tensor)

CPU times: user 65 µs, sys: 11 µs, total: 76 µs
Wall time: 81.1 µs


tensor(35)

In [56]:
%%time
my_tensor @ my_tensor

CPU times: user 164 µs, sys: 0 ns, total: 164 µs
Wall time: 190 µs


tensor(35)

### Shape ERRORS!!!!

In [57]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [58]:
tensor_B = torch.tensor([
  [7, 10],
  [8, 11],
  [9, 12] 
])

tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [59]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [60]:
tensor_B.T , tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [61]:
tensor_B.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [62]:
try:
  torch.mm(tensor_A, tensor_B)
except:
  print(r"""RuntimeError                              Traceback (most recent call last)
<ipython-input-210-d49420418508> in <module>
----> 1 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)""")

RuntimeError                              Traceback (most recent call last)
<ipython-input-210-d49420418508> in <module>
----> 1 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [63]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [64]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [65]:
tensor_A.shape , tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### finding the min, max, mean, sum, etc

In [66]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
# min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [68]:
# max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [69]:
# mean
try:
  torch.mean(x)
except:
  print("change dtype")
  print("RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long")

change dtype
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [70]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [71]:
# mean
try:
  x.mean()
except:
  print("change dtype")
  print("mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long")

change dtype
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [72]:
x.type(torch.float32).mean()

tensor(45.)

### Finding the position min and max

In [73]:
y =torch.tensor( [22 , 10 , 20 , 0, 30, 40, 5, 60, 70, 89, 449])
y

tensor([ 22,  10,  20,   0,  30,  40,   5,  60,  70,  89, 449])

In [74]:
# find the position of min val and return the index of min val
y.argmin()

tensor(3)

In [75]:
y[3]

tensor(0)

In [76]:
# find the position of max val and return the index of max val
y.argmax()

tensor(10)

In [77]:
y[10]

tensor(449)

### Reshaping, Stacking, Squeezing & UNsqueezing tensors

In [78]:
import torch

In [81]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [83]:
try:  
  x_reshaped = x.reshape(1,7)
  x_reshaped, x_reshaped.shape
except:
  print("""RuntimeError                              Traceback (most recent call last)
<ipython-input-82-4b29e0ec9aba> in <module>
----> 1 x_reshaped = x.reshape(1,7)
      2 x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9""")

RuntimeError                              Traceback (most recent call last)
<ipython-input-82-4b29e0ec9aba> in <module>
----> 1 x_reshaped = x.reshape(1,7)
      2 x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9


In [87]:
#change shape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [89]:
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [90]:
x_reshape = x.reshape(3,4)
x_reshape, x_reshape.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]), torch.Size([3, 4]))

In [96]:
x = torch.arange(1,10)
x_reshaped = x.reshape(1,9)

### changing view
x.view and x share same memory so if you change the x.view it will change the original x.

In [97]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [98]:
z[:, 4] = 12
z, x

(tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]]),
 tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9]))

### Stack tensors

In [99]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9]])

In [100]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [12, 12, 12, 12],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9]])

In [101]:
x_stacked = torch.stack([x, x, x, x], dim=-1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [12, 12, 12, 12],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9]])

In [103]:
x_stacked = torch.stack([x, x, x, x], dim=-2)
x_stacked

tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9]])

### squeeze
remove single dim

In [108]:
print(x_reshaped)
print(x_reshaped.shape)
print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)

tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]])
torch.Size([1, 9])
tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
torch.Size([9])


In [114]:
x_reshape =x.reshape(3,1,3)
print(x_reshape)
print(x_reshape.shape)
print(x_reshape.squeeze())
print(x_reshape.squeeze().shape)

tensor([[[ 1,  2,  3]],

        [[ 4, 12,  6]],

        [[ 7,  8,  9]]])
torch.Size([3, 1, 3])
tensor([[ 1,  2,  3],
        [ 4, 12,  6],
        [ 7,  8,  9]])
torch.Size([3, 3])


In [116]:
#torch.squeeze remove all the 1 dim
#example:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

print()
#removing extera dims
print(f"New tensor: {x_reshaped.squeeze()}")
print(f"New shape: {x_reshaped.squeeze().shape}")


previous tensor: tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]])
previous shape: torch.Size([1, 9])

New tensor: tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
New shape: torch.Size([9])


### unsqueeze
add single dim

In [123]:
#example:
print(f"previous tensor: {x_reshaped.squeeze()}")
print(f"previous shape: {x_reshaped.squeeze().shape}")
print(f"previous dim: {x_reshaped.squeeze().ndim}")


print()
#adding extera dim0
print(f"New tensor: {x_reshaped.squeeze().unsqueeze(dim=0)}")
print(f"New shape: {x_reshaped.squeeze().unsqueeze(dim=0).shape}")
print(f"New dim: {x_reshaped.squeeze().unsqueeze(dim=0).ndim}")

previous tensor: tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
previous shape: torch.Size([9])
previous dim: 1

New tensor: tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]])
New shape: torch.Size([1, 9])
New dim: 2


In [124]:
#example:
print(f"previous tensor: {x_reshaped.squeeze()}")
print(f"previous shape: {x_reshaped.squeeze().shape}")
print(f"previous dim: {x_reshaped.squeeze().ndim}")


print()
#adding extera dim1
print(f"New tensor: {x_reshaped.squeeze().unsqueeze(dim=1)}")
print(f"New shape: {x_reshaped.squeeze().unsqueeze(dim=1).shape}")
print(f"New dim: {x_reshaped.squeeze().unsqueeze(dim=1).ndim}")

previous tensor: tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
previous shape: torch.Size([9])
previous dim: 1

New tensor: tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [12],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])
New shape: torch.Size([9, 1])
New dim: 2


### permute
mostly in images 
return view


In [131]:
x_orginal = torch.rand(size=(224, 224, 3)) # (h,W,color channel) of image

# permute the original to rearenge of axises
x_permuted = x_orginal.permute(2, 0, 1) # axis0-> axis1 , axis1-> axis2 , axis2 -> axis0

print(f"Previous shape: {x_orginal.shape}")
print(f"New shape: {x_permuted.shape}") # (color channel, h, w)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [133]:
print("pre x_org[0,0,0]=",x_orginal[0, 0, 0])
print("pre x_permuted[0,0,0]=",x_permuted[0,0,0])
#changing x_org to show that permute return different view version of x_org and share same memory
x_orginal[0,0,0] =12
print("x_orginal[0,0,0]=",x_orginal[0,0,0])
print("x_permuted[0,0,0]=",x_permuted[0,0,0])

pre x_org[0,0,0]= tensor(12.)
pre x_permuted[0,0,0]= tensor(12.)
x_orginal[0,0,0]= tensor(12.)
x_permuted[0,0,0]= tensor(12.)


### Indexing 
indexing with torch is similar to Numpy

In [134]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [136]:
# indexing
print("x[0]= ", x[0])

x[0]=  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [139]:
#index middle bracket
print("x[0][0]= ", x[0][0])
print("x[0,0]= ", x[0, 0])

x[0][0]=  tensor([1, 2, 3])
x[0,0]=  tensor([1, 2, 3])


In [142]:
#index most inner bracket
print("x[0][0][0]=", x[0][0][0])
print("x[0,0,0]=", x[0, 0, 0])

x[0][0][0]= tensor(1)
x[0,0,0]= tensor(1)


In [143]:
x[0][0][1]

tensor(2)

In [146]:
#getting num 9
x[0][2][2]

tensor(9)

In [147]:
#getting all the dim with ":"
x[:, 0]

tensor([[1, 2, 3]])

In [148]:
# get all vals of 0th and 1st dim only index 1 of second dim

x[:, :, 1]

tensor([[2, 5, 8]])

In [150]:
# get all vals of 0th and  dim only index 1 of first second dim
x[:,1,1],x[0,1,1]

(tensor([5]), tensor(5))

In [151]:
# get index 0  of 0th and 1st dim all values of  second dim
x[0,0,:]

tensor([1, 2, 3])

In [153]:
#return 3,6,9
x[0,:,2], x[:,:,2]


(tensor([3, 6, 9]), tensor([[3, 6, 9]]))

### PyTorch tensors & NmPy