<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [1]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [2]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as python int
scalar.item()

7

## Vectors

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

## MATRIX

In [10]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


## TENSOR

In [14]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [18]:
TENSOR2.ndim

3

In [19]:
TENSOR2.shape

torch.Size([2, 3, 3])

### RAndom TenSors
Neural Network start learning with Random Tensors

In [20]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3764, 0.9573, 0.7333, 0.5938],
        [0.8032, 0.7233, 0.0011, 0.0955],
        [0.5812, 0.8013, 0.0570, 0.0169]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor2 = torch.rand(5, 5, 10)
random_tensor2

tensor([[[0.4201, 0.2569, 0.2540, 0.2569, 0.3366, 0.9910, 0.4777, 0.6815,
          0.7603, 0.7765],
         [0.1552, 0.6553, 0.0633, 0.8691, 0.1155, 0.1196, 0.2158, 0.0055,
          0.7923, 0.6500],
         [0.4712, 0.1249, 0.3363, 0.3856, 0.3387, 0.6480, 0.0269, 0.7228,
          0.3512, 0.2610],
         [0.5947, 0.0993, 0.9589, 0.1783, 0.8839, 0.0873, 0.4185, 0.9986,
          0.3334, 0.4990],
         [0.8478, 0.3537, 0.6112, 0.1101, 0.1232, 0.0176, 0.3393, 0.3137,
          0.5904, 0.5101]],

        [[0.2130, 0.3943, 0.3963, 0.4989, 0.8906, 0.9101, 0.6831, 0.2643,
          0.9418, 0.5560],
         [0.9363, 0.7485, 0.0329, 0.7851, 0.9811, 0.1247, 0.6425, 0.4479,
          0.2623, 0.0302],
         [0.8204, 0.4898, 0.8590, 0.2014, 0.9442, 0.0269, 0.9646, 0.8438,
          0.7081, 0.4915],
         [0.1347, 0.6362, 0.0570, 0.9386, 0.1734, 0.6632, 0.0149, 0.9886,
          0.4119, 0.1831],
         [0.6997, 0.2578, 0.7046, 0.2755, 0.6899, 0.7412, 0.2860, 0.9252,
          0.214

In [23]:
random_tensor2.ndim

3

In [24]:
# Creat a random tensor similar to shape of image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h,w,color channels
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [25]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
torch.rand(3,4) * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zero.dtype

torch.float32

In [28]:
# Ones
one = torch.ones(5,6,7)
one

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1.,

In [29]:
one.dtype

torch.float32

## creating range of tensors and tensor like

In [30]:
torch.range(1,10)

<ipython-input-30-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
torch.arange(start=1, end=1000, step=63)

tensor([  1,  64, 127, 190, 253, 316, 379, 442, 505, 568, 631, 694, 757, 820,
        883, 946])

## Tensor like

In [33]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [34]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=None)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [35]:
float_16_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 4., 5., 6.], dtype=torch.float16)
torch.float16


In [36]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device=None,
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [38]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device='cpu',
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5., 6.], dtype=torch.float16)

In [42]:
m = float_16_tensor * float_32_tensor
print(m)
print(m.dtype)

tensor([ 9., 16., 25., 36.])
torch.float32


In [43]:
m = float_16_tensor * float_16_tensor
m

tensor([ 9., 16., 25., 36.], dtype=torch.float16)

In [44]:
int_32_tensor = torch.tensor([3, 7, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

Most important Error

In [47]:
# float_32_tensor * int_32_tensor 

RuntimeError: ignored

In [45]:
# int_32_tensor * float_16_tensor

RuntimeError: ignored

## Getting information from Tensors 

In [48]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2498, 0.1395, 0.8634, 0.1662],
        [0.4230, 0.4257, 0.9295, 0.7403],
        [0.1584, 0.2128, 0.6606, 0.2321]])

In [49]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2498, 0.1395, 0.8634, 0.1662],
        [0.4230, 0.4257, 0.9295, 0.7403],
        [0.1584, 0.2128, 0.6606, 0.2321]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

In [50]:
my_tensor = torch.tensor([1, 3, 5])
my_tensor + 10

tensor([11, 13, 15])

In [51]:
my_tensor * 10

tensor([10, 30, 50])

In [52]:
my_tensor - 10

tensor([-9, -7, -5])

## Built in functions 

In [55]:
torch.mul(my_tensor , 10)

tensor([10, 30, 50])

In [56]:
torch.add(my_tensor, 10)

tensor([11, 13, 15])

## Matrix Multiplication

In [58]:
print(my_tensor, "*", my_tensor)
my_tensor * my_tensor

tensor([1, 3, 5]) * tensor([1, 3, 5])


tensor([ 1,  9, 25])

In [59]:
torch.matmul(my_tensor, my_tensor)

tensor(35)

In [60]:
#matrix multi by hand
1*1 + 3*3 + 5*5

35

In [63]:
%%time
v=0
for i in my_tensor:
  v += i * i
print(v) 

tensor(35)
CPU times: user 2.48 ms, sys: 0 ns, total: 2.48 ms
Wall time: 2.43 ms


In [64]:
%%time
torch.matmul(my_tensor, my_tensor)

CPU times: user 230 µs, sys: 22 µs, total: 252 µs
Wall time: 257 µs


tensor(35)