<a href="https://colab.research.google.com/github/zahra-sharifzadeh/pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

In [2]:
print("Hello I'm Excited to learn Pytorch")

Hello I'm Excited to learn Pytorch


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


# Introduction to Tensors
 ## Creating tensors

## scalar

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

7

## Vectors

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

## MATRIX

In [11]:
MATRIX = torch.tensor([
    [2, 3],
    [4, 5]
])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
print(MATRIX[0])
print("*"*20)
print(MATRIX[1])

tensor([2, 3])
********************
tensor([4, 5])


## TENSOR

In [15]:
TENSOR = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR2= torch.tensor([
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,11,12],
    [12,13,14],
    [15,16,17]]

])
TENSOR2

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [12, 13, 14],
         [15, 16, 17]]])

In [19]:
TENSOR2.ndim

3

In [20]:
TENSOR2.shape

torch.Size([2, 3, 3])

### RAndom TenSors
Neural Network start learning with Random Tensors

In [21]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3497, 0.1314, 0.1602, 0.9091],
        [0.7243, 0.9688, 0.8912, 0.2219],
        [0.3369, 0.5911, 0.2812, 0.3976]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor2 = torch.rand(5, 5, 10)
random_tensor2

tensor([[[0.3833, 0.9724, 0.6656, 0.8230, 0.6591, 0.1811, 0.0016, 0.8471,
          0.3082, 0.7984],
         [0.1493, 0.5134, 0.8641, 0.6117, 0.2041, 0.8237, 0.7116, 0.0200,
          0.2285, 0.4774],
         [0.1133, 0.1236, 0.8963, 0.5233, 0.7906, 0.3134, 0.9208, 0.9321,
          0.0143, 0.0680],
         [0.4049, 0.3646, 0.2643, 0.2656, 0.1758, 0.3212, 0.2241, 0.5120,
          0.0527, 0.2708],
         [0.2237, 0.9508, 0.2639, 0.2683, 0.1294, 0.8231, 0.9502, 0.3862,
          0.1009, 0.2718]],

        [[0.2482, 0.5524, 0.1938, 0.0225, 0.3031, 0.1162, 0.2803, 0.0116,
          0.0104, 0.3696],
         [0.4860, 0.8053, 0.3633, 0.0637, 0.2952, 0.8317, 0.6741, 0.1024,
          0.5252, 0.8677],
         [0.6050, 0.8118, 0.4171, 0.5598, 0.5135, 0.6843, 0.3922, 0.3746,
          0.8939, 0.0920],
         [0.2493, 0.6515, 0.8435, 0.0630, 0.7814, 0.3851, 0.6339, 0.6765,
          0.9522, 0.4914],
         [0.1381, 0.7003, 0.3993, 0.2009, 0.7597, 0.7547, 0.7837, 0.5135,
          0.421

In [24]:
random_tensor2.ndim

3

In [25]:
# Creat a random tensor similar to shape of image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # h,w,color channels
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [26]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
torch.rand(3,4) * zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zero.dtype

torch.float32

In [29]:
# Ones
one = torch.ones(5,6,7)
one

tensor([[[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1.],
         [1., 1.,

In [30]:
one.dtype

torch.float32

### creating range of tensors and tensor like

In [31]:
torch.range(1,10)

<ipython-input-31-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
torch.arange(start=1, end=1000, step=63)

tensor([  1,  64, 127, 190, 253, 316, 379, 442, 505, 568, 631, 694, 757, 820,
        883, 946])

### Tensor like

In [34]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

In [35]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=None)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [36]:
float_16_tensor = torch.tensor([3.0, 4.0, 5.0, 6.0], dtype=torch.float16)
print(float_16_tensor)
print(float_16_tensor.dtype)

tensor([3., 4., 5., 6.], dtype=torch.float16)
torch.float16


In [37]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device=None,
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [38]:
a = torch.tensor([3.0, 4.0, 5.0, 6.0], 
                 dtype=None,
                 device='cpu',
                 requires_grad=False
                 )
print(a)
print(a.dtype)

tensor([3., 4., 5., 6.])
torch.float32


In [39]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5., 6.], dtype=torch.float16)

In [40]:
m = float_16_tensor * float_32_tensor
print(m)
print(m.dtype)

tensor([ 9., 16., 25., 36.])
torch.float32


In [41]:
m = float_16_tensor * float_16_tensor
m

tensor([ 9., 16., 25., 36.], dtype=torch.float16)

In [42]:
int_32_tensor = torch.tensor([3, 7, 8], dtype=torch.int32)
int_32_tensor

tensor([3, 7, 8], dtype=torch.int32)

Most important Error

In [43]:
# float_32_tensor * int_32_tensor 

In [44]:
# int_32_tensor * float_16_tensor

### Getting information from Tensors 

In [45]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1634, 0.5744, 0.2710, 0.8795],
        [0.0408, 0.9243, 0.1785, 0.4612],
        [0.5768, 0.5165, 0.0030, 0.2805]])

In [46]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1634, 0.5744, 0.2710, 0.8795],
        [0.0408, 0.9243, 0.1785, 0.4612],
        [0.5768, 0.5165, 0.0030, 0.2805]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

In [47]:
%%time
my_tensor = torch.tensor([1, 3, 5])
my_tensor + 10

CPU times: user 1.3 ms, sys: 36 µs, total: 1.34 ms
Wall time: 3.19 ms


tensor([11, 13, 15])

In [48]:
%%time
my_tensor * 10

CPU times: user 0 ns, sys: 1.18 ms, total: 1.18 ms
Wall time: 935 µs


tensor([10, 30, 50])

In [49]:
%%time
my_tensor - 10

CPU times: user 2.2 ms, sys: 0 ns, total: 2.2 ms
Wall time: 6.56 ms


tensor([-9, -7, -5])

### Built in functions 

In [50]:
%%time
torch.mul(my_tensor , 10)

CPU times: user 89 µs, sys: 11 µs, total: 100 µs
Wall time: 105 µs


tensor([10, 30, 50])

In [51]:
%%time
torch.add(my_tensor, 10)

CPU times: user 108 µs, sys: 14 µs, total: 122 µs
Wall time: 125 µs


tensor([11, 13, 15])

### Matrix Multiplication

In [52]:
print(my_tensor, "*", my_tensor)
my_tensor * my_tensor

tensor([1, 3, 5]) * tensor([1, 3, 5])


tensor([ 1,  9, 25])

In [53]:
torch.matmul(my_tensor, my_tensor)

tensor(35)

In [54]:
#matrix multi by hand
1*1 + 3*3 + 5*5

35

In [55]:
%%time
v=0
for i in my_tensor:
  v += i * i
print(v) 

tensor(35)
CPU times: user 1.59 ms, sys: 73 µs, total: 1.67 ms
Wall time: 1.28 ms


In [56]:
%%time
torch.matmul(my_tensor, my_tensor)

CPU times: user 1.47 ms, sys: 57 µs, total: 1.53 ms
Wall time: 1.61 ms


tensor(35)

In [57]:
%%time
my_tensor @ my_tensor

CPU times: user 125 µs, sys: 15 µs, total: 140 µs
Wall time: 145 µs


tensor(35)

### Shape ERRORS!!!!

In [58]:
tensor_A = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [59]:
tensor_B = torch.tensor([
  [7, 10],
  [8, 11],
  [9, 12] 
])

tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [60]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [61]:
tensor_B.T , tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [62]:
tensor_B.T.shape , tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [63]:
try:
  torch.mm(tensor_A, tensor_B)
except:
  print(r"""RuntimeError                              Traceback (most recent call last)
<ipython-input-210-d49420418508> in <module>
----> 1 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)""")

RuntimeError                              Traceback (most recent call last)
<ipython-input-210-d49420418508> in <module>
----> 1 torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)


In [64]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [65]:
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

In [66]:
tensor_A.shape , tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

### finding the min, max, mean, sum, etc

In [67]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [68]:
# min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [69]:
# max
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [70]:
# mean
try:
  torch.mean(x)
except:
  print("change dtype")
  print("RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long")

change dtype
RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [71]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [72]:
# mean
try:
  x.mean()
except:
  print("change dtype")
  print("mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long")

change dtype
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [73]:
x.type(torch.float32).mean()

tensor(45.)

### Finding the position min and max

In [74]:
y =torch.tensor( [22 , 10 , 20 , 0, 30, 40, 5, 60, 70, 89, 449])
y

tensor([ 22,  10,  20,   0,  30,  40,   5,  60,  70,  89, 449])

In [75]:
# find the position of min val and return the index of min val
y.argmin()

tensor(3)

In [76]:
y[3]

tensor(0)

In [77]:
# find the position of max val and return the index of max val
y.argmax()

tensor(10)

In [78]:
y[10]

tensor(449)

### Reshaping, Stacking, Squeezing & UNsqueezing tensors

In [79]:
import torch

In [80]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [81]:
try:  
  x_reshaped = x.reshape(1,7)
  x_reshaped, x_reshaped.shape
except:
  print("""RuntimeError                              Traceback (most recent call last)
<ipython-input-82-4b29e0ec9aba> in <module>
----> 1 x_reshaped = x.reshape(1,7)
      2 x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9""")

RuntimeError                              Traceback (most recent call last)
<ipython-input-82-4b29e0ec9aba> in <module>
----> 1 x_reshaped = x.reshape(1,7)
      2 x_reshaped, x_reshaped.shape

RuntimeError: shape '[1, 7]' is invalid for input of size 9


In [82]:
#change shape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [83]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [84]:
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [85]:
x_reshape = x.reshape(3,4)
x_reshape, x_reshape.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]), torch.Size([3, 4]))

In [86]:
x = torch.arange(1,10)
x_reshaped = x.reshape(1,9)

### changing view
x.view and x share same memory so if you change the x.view it will change the original x.

In [87]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [88]:
z[:, 4] = 12
z, x

(tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]]),
 tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9]))

### Stack tensors

In [89]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9]])

In [90]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [12, 12, 12, 12],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9]])

In [91]:
x_stacked = torch.stack([x, x, x, x], dim=-1)
x_stacked

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [12, 12, 12, 12],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9]])

In [92]:
x_stacked = torch.stack([x, x, x, x], dim=-2)
x_stacked

tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9],
        [ 1,  2,  3,  4, 12,  6,  7,  8,  9]])

### squeeze
remove single dim

In [93]:
print(x_reshaped)
print(x_reshaped.shape)
print(x_reshaped.squeeze())
print(x_reshaped.squeeze().shape)

tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]])
torch.Size([1, 9])
tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
torch.Size([9])


In [94]:
x_reshape =x.reshape(3,1,3)
print(x_reshape)
print(x_reshape.shape)
print(x_reshape.squeeze())
print(x_reshape.squeeze().shape)

tensor([[[ 1,  2,  3]],

        [[ 4, 12,  6]],

        [[ 7,  8,  9]]])
torch.Size([3, 1, 3])
tensor([[ 1,  2,  3],
        [ 4, 12,  6],
        [ 7,  8,  9]])
torch.Size([3, 3])


In [95]:
#torch.squeeze remove all the 1 dim
#example:
print(f"previous tensor: {x_reshaped}")
print(f"previous shape: {x_reshaped.shape}")

print()
#removing extera dims
print(f"New tensor: {x_reshaped.squeeze()}")
print(f"New shape: {x_reshaped.squeeze().shape}")


previous tensor: tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]])
previous shape: torch.Size([1, 9])

New tensor: tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
New shape: torch.Size([9])


### unsqueeze
add single dim

In [96]:
#example:
print(f"previous tensor: {x_reshaped.squeeze()}")
print(f"previous shape: {x_reshaped.squeeze().shape}")
print(f"previous dim: {x_reshaped.squeeze().ndim}")


print()
#adding extera dim0
print(f"New tensor: {x_reshaped.squeeze().unsqueeze(dim=0)}")
print(f"New shape: {x_reshaped.squeeze().unsqueeze(dim=0).shape}")
print(f"New dim: {x_reshaped.squeeze().unsqueeze(dim=0).ndim}")

previous tensor: tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
previous shape: torch.Size([9])
previous dim: 1

New tensor: tensor([[ 1,  2,  3,  4, 12,  6,  7,  8,  9]])
New shape: torch.Size([1, 9])
New dim: 2


In [97]:
#example:
print(f"previous tensor: {x_reshaped.squeeze()}")
print(f"previous shape: {x_reshaped.squeeze().shape}")
print(f"previous dim: {x_reshaped.squeeze().ndim}")


print()
#adding extera dim1
print(f"New tensor: {x_reshaped.squeeze().unsqueeze(dim=1)}")
print(f"New shape: {x_reshaped.squeeze().unsqueeze(dim=1).shape}")
print(f"New dim: {x_reshaped.squeeze().unsqueeze(dim=1).ndim}")

previous tensor: tensor([ 1,  2,  3,  4, 12,  6,  7,  8,  9])
previous shape: torch.Size([9])
previous dim: 1

New tensor: tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [12],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])
New shape: torch.Size([9, 1])
New dim: 2


### permute
mostly in images 
return view


In [98]:
x_orginal = torch.rand(size=(224, 224, 3)) # (h,W,color channel) of image

# permute the original to rearenge of axises
x_permuted = x_orginal.permute(2, 0, 1) # axis0-> axis1 , axis1-> axis2 , axis2 -> axis0

print(f"Previous shape: {x_orginal.shape}")
print(f"New shape: {x_permuted.shape}") # (color channel, h, w)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [99]:
print("pre x_org[0,0,0]=",x_orginal[0, 0, 0])
print("pre x_permuted[0,0,0]=",x_permuted[0,0,0])
#changing x_org to show that permute return different view version of x_org and share same memory
x_orginal[0,0,0] =12
print("x_orginal[0,0,0]=",x_orginal[0,0,0])
print("x_permuted[0,0,0]=",x_permuted[0,0,0])

pre x_org[0,0,0]= tensor(0.8971)
pre x_permuted[0,0,0]= tensor(0.8971)
x_orginal[0,0,0]= tensor(12.)
x_permuted[0,0,0]= tensor(12.)


### Indexing 
indexing with torch is similar to Numpy

In [100]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [101]:
# indexing
print("x[0]= ", x[0])

x[0]=  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [102]:
#index middle bracket
print("x[0][0]= ", x[0][0])
print("x[0,0]= ", x[0, 0])

x[0][0]=  tensor([1, 2, 3])
x[0,0]=  tensor([1, 2, 3])


In [103]:
#index most inner bracket
print("x[0][0][0]=", x[0][0][0])
print("x[0,0,0]=", x[0, 0, 0])

x[0][0][0]= tensor(1)
x[0,0,0]= tensor(1)


In [104]:
x[0][0][1]

tensor(2)

In [105]:
#getting num 9
x[0][2][2]

tensor(9)

In [106]:
#getting all the dim with ":"
x[:, 0]

tensor([[1, 2, 3]])

In [107]:
# get all vals of 0th and 1st dim only index 1 of second dim

x[:, :, 1]

tensor([[2, 5, 8]])

In [108]:
# get all vals of 0th and  dim only index 1 of first second dim
x[:,1,1],x[0,1,1]

(tensor([5]), tensor(5))

In [109]:
# get index 0  of 0th and 1st dim all values of  second dim
x[0,0,:]

tensor([1, 2, 3])

In [110]:
#return 3,6,9
x[0,:,2], x[:,:,2]


(tensor([3, 6, 9]), tensor([[3, 6, 9]]))

### PyTorch tensors & NmPy

In [111]:
import numpy as np

In [112]:
# Nmpy to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [113]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [114]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [115]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32) # numpy defult dtype is float64
print(array, tensor)
print(array.dtype, tensor.dtype)

[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.])
float64 torch.float32


In [116]:
array = array + 1
array, tensor
# from_numpy will make New tensor and it does not share memory

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [117]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor , numpy_tensor)
print(tensor.dtype , numpy_tensor.dtype)


tensor([1., 1., 1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1. 1. 1.]
torch.float32 float32


In [118]:
tensor = tensor + 1
tensor , numpy_tensor
# they don't share memory

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

###035-PyTorch Reproducibility Taking the Random Out of Random
reduce the randomness by  **Random Seed**

In [121]:
#creat 2 random tesor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print("A=", random_tensor_A)
print("B=", random_tensor_B)
print(random_tensor_A == random_tensor_B)

A= tensor([[0.5928, 0.9568, 0.4789, 0.9850],
        [0.9553, 0.8740, 0.9309, 0.3263],
        [0.5598, 0.3949, 0.8214, 0.0951]])
B= tensor([[0.0178, 0.3442, 0.7371, 0.1387],
        [0.4937, 0.1903, 0.7278, 0.3492],
        [0.8087, 0.9637, 0.0381, 0.7200]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])
