# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch 
tensor = torch.rand(7, 7)
tensor
# Create random tensor


tensor([[0.4779, 0.2945, 0.7924, 0.9635, 0.6021, 0.5427, 0.1206],
        [0.8848, 0.0303, 0.9821, 0.3435, 0.5601, 0.0274, 0.3704],
        [0.9762, 0.8737, 0.7025, 0.9413, 0.2076, 0.1213, 0.9419],
        [0.4519, 0.0237, 0.2542, 0.7958, 0.7255, 0.5584, 0.0010],
        [0.6404, 0.8517, 0.1097, 0.1799, 0.5411, 0.4508, 0.1885],
        [0.9761, 0.9843, 0.4523, 0.5420, 0.1293, 0.6624, 0.8094],
        [0.5765, 0.2516, 0.5440, 0.5642, 0.4376, 0.3757, 0.4436]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tensor_A = torch.rand(7,7)
tensor_B = torch.rand(1,7)

print(torch.mm(tensor_A, tensor_B.T))
print(torch.mm(tensor_B, tensor_A))
# Perform matrix multiplication 


tensor([[2.0156],
        [1.3810],
        [2.6044],
        [1.8332],
        [1.7296],
        [1.8684],
        [2.1028]])
tensor([[2.1741, 1.5141, 3.2021, 1.7229, 1.1095, 1.9557, 1.5834]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_A = torch.rand(7,7)

tensor_B = torch.rand(1,7)

# Matrix multiply tensors
m = torch.mm(tensor_A, tensor_B.T)
print(m, m.shape )


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [13]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [17]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_C = torch.rand(size=(2,3)).to(device)
tensor_D = torch.rand(size=(2,3)).to(device)
tensor_C, tensor_D

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
multi = torch.mm(tensor_C, tensor_D.T)
multi

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [22]:
# Find max
print("max =",multi.max())
# Find min
print("min =", multi.min())

max = tensor(0.5617, device='cuda:0')
min = tensor(0.3647, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print("max =",multi.argmax())


# Find arg min
print("min =", multi.argmin())

max = tensor(3, device='cuda:0')
min = tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(7)

# Create random tensor
x = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
x_squeezed = x.squeeze()

# Print out tensors and their shapes
print(x, x.shape)
print(x_squeezed, x_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
